window.norwegianNameOverrides = {
  // --- Europa ---
  'ALB': 'Albania', 'albania': 'Albania',
  'AND': 'Andorra', 'andorra': 'Andorra',
  'AUT': 'Østerrike', 'austria': 'Østerrike',
  'BEL': 'Belgia', 'belgium': 'Belgia',
  'BGR': 'Bulgaria', 'bulgaria': 'Bulgaria',
  'BIH': 'Bosnia-Hercegovina', 'bosnia and herzegovina': 'Bosnia-Hercegovina',
  'BLR': 'Hviterussland', 'belarus': 'Hviterussland',
  'CHE': 'Sveits', 'switzerland': 'Sveits',
  'CYP': 'Kypros', 'cyprus': 'Kypros',
  'CZE': 'Tsjekkia', 'czech republic': 'Tsjekkia', 'czechia': 'Tsjekkia',
  'DEU': 'Tyskland', 'germany': 'Tyskland',
  'DNK': 'Danmark', 'denmark': 'Danmark',
  'ESP': 'Spania', 'spain': 'Spania',
  'EST': 'Estland', 'estonia': 'Estland',
  'FIN': 'Finland',
  'FRA': 'Frankrike', 'france': 'Frankrike',
  'FRO': 'Færøyene', 'faroe islands': 'Færøyene',
  'GBR': 'Storbritannia', 'united kingdom': 'Storbritannia',
  'GEO': 'Georgia',
  'GIB': 'Gibraltar',
  'GRC': 'Hellas', 'greece': 'Hellas',
  'HRV': 'Kroatia', 'croatia': 'Kroatia',
  'HUN': 'Ungarn', 'hungary': 'Ungarn',
  'IRL': 'Irland', 'ireland': 'Irland',
  'ISL': 'Island', 'iceland': 'Island',
  'ITA': 'Italia', 'italy': 'Italia',
  'KOS': 'Kosovo',
  'LIE': 'Liechtenstein',
  'LTU': 'Litauen', 'lithuania': 'Litauen',
  'LUX': 'Luxembourg',
  'LVA': 'Letland', 'latvia': 'Letland',
  'MCO': 'Monaco',
  'MDA': 'Moldova',
  'MKD': 'Nord-Makedonia', 'macedonia': 'Nord-Makedonia', 'north macedonia': 'Nord-Makedonia',
  'MLT': 'Malta',
  'MNE': 'Montenegro',
  'NLD': 'Nederland', 'netherlands': 'Nederland',
  'NOR': 'Norge', 'norway': 'Norge',
  'POL': 'Polen', 'poland': 'Polen',
  'PRT': 'Portugal',
  'ROU': 'Romania',
  'RUS': 'Russland', 'russia': 'Russland', 'RUS-ASIA': 'Russland (Asia)',
  'SMR': 'San Marino',
  'SRB': 'Serbia',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SWE': 'Sverige', 'sweden': 'Sverige',
  'UKR': 'Ukraina', 'ukraine': 'Ukraina',
  'VAT': 'Vatikanstaten', 'vatican city': 'Vatikanstaten',
  'ARM': 'Armenia',
  'AZE': 'Aserbajdsjan', 'azerbaijan': 'Aserbajdsjan',
  'KAZ': 'Kasakhstan', 'kazakhstan': 'Kasakhstan',
  'TUR': 'Tyrkia', 'turkey': 'Tyrkia',
  'ALA': 'Åland', 'aland islands': 'Åland',

  // --- Nord-Amerika & Karibia ---
  'ABW': 'Aruba',
  'AIA': 'Anguilla',
  'ATG': 'Antigua og Barbuda', 'antigua and barbuda': 'Antigua og Barbuda',
  'BHS': 'Bahamas', 'the bahamas': 'Bahamas',
  'BLZ': 'Belize',
  'BMU': 'Bermuda',
  'BRB': 'Barbados',
  'CAN': 'Kanada', 'canada': 'Kanada',
  'CRI': 'Costa Rica',
  'CUB': 'Kuba', 'cuba': 'Kuba',
  'CYM': 'Caymanøyene', 'cayman islands': 'Caymanøyene',
  'DMA': 'Dominica',
  'DOM': 'Den dominikanske republikk', 'dominican republic': 'Den dominikanske republikk',
  'GLP': 'Guadeloupe',
  'GRD': 'Grenada',
  'GRL': 'Grønland', 'greenland': 'Grønland',
  'GTM': 'Guatemala',
  'HND': 'Honduras',
  'HTI': 'Haiti',
  'JAM': 'Jamaica',
  'LCA': 'Saint Lucia',
  'MEX': 'Meksiko', 'mexico': 'Meksiko',
  'MTQ': 'Martinique',
  'NIC': 'Nicaragua',
  'PAN': 'Panama',
  'PRI': 'Puerto Rico',
  'SLV': 'El Salvador',
  'TTO': 'Trinidad og Tobago', 'trinidad and tobago': 'Trinidad og Tobago',
  'USA': 'USA', 'united states of america': 'USA', 'united states': 'USA',
  'VCT': 'Saint Vincent og Grenadinene', 'saint vincent and the grenadines': 'Saint Vincent og Grenadinene',
  'VIR': 'De amerikanske Jomfruøyer', 'united states virgin islands': 'De amerikanske Jomfruøyer',

  // --- Sør-Amerika ---
  'ARG': 'Argentina',
  'BOL': 'Bolivia',
  'BRA': 'Brasil', 'brazil': 'Brasil',
  'CHL': 'Chile',
  'COL': 'Colombia',
  'ECU': 'Ecuador',
  'FLK': 'Falklandsøyene', 'falkland islands': 'Falklandsøyene',
  'GUF': 'Fransk Guyana', 'french guiana': 'Fransk Guyana',
  'GUY': 'Guyana',
  'PER': 'Peru',
  'PRY': 'Paraguay',
  'SUR': 'Surinam', 'suriname': 'Surinam',
  'URY': 'Uruguay',
  'VEN': 'Venezuela',

  // --- Asia ---
  'AFG': 'Afghanistan',
  'ARE': 'De forente arabiske emirater', 'united arab emirates': 'De forente arabiske emirater',
  'BGD': 'Bangladesh',
  'BHR': 'Bahrain',
  'BRN': 'Brunei',
  'BTN': 'Bhutan',
  'CHN': 'Kina', 'china': 'Kina',
  'IDN': 'Indonesia',
  'IND': 'India',
  'ISR': 'Israel',
  'JOR': 'Jordan',
  'JPN': 'Japan',
  'KGZ': 'Kirgisistan', 'kyrgyzstan': 'Kirgisistan',
  'KHM': 'Kambodsja', 'cambodia': 'Kambodsja',
  'KOR': 'Sør-Korea', 'south korea': 'Sør-Korea', 'korea, republic of': 'Sør-Korea',
  'KWT': 'Kuwait',
  'LAO': 'Laos',
  'LBN': 'Libanon', 'lebanon': 'Libanon',
  'LKA': 'Sri Lanka',
  'MDV': 'Maldivene', 'maldives': 'Maldivene',
  'MMR': 'Myanmar',
  'MNG': 'Mongolia',
  'MYS': 'Malaysia',
  'NPL': 'Nepal',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PHL': 'Filippinene', 'philippines': 'Filippinene',
  'PRK': 'Nord-Korea', 'north korea': 'Nord-Korea', 'dem. rep. korea': 'Nord-Korea',
  'PSE': 'Palestina', 'palestine': 'Palestina',
  'QAT': 'Qatar',
  'SAU': 'Saudi-Arabia', 'saudi arabia': 'Saudi-Arabia',
  'SGP': 'Singapore',
  'SYR': 'Syria',
  'THA': 'Thailand',
  'TJK': 'Tadsjikistan', 'tajikistan': 'Tadsjikistan',
  'TKM': 'Turkmenistan',
  'TLS': 'Øst-Timor', 'east timor': 'Øst-Timor', 'timor-leste': 'Øst-Timor',
  'TWN': 'Taiwan',
  'UZB': 'Usbekistan', 'uzbekistan': 'Usbekistan',
  'VNM': 'Vietnam',
  'YEM': 'Jemen', 'yemen': 'Jemen',

  // --- Afrika ---
  'AGO': 'Angola',
  'BDI': 'Burundi',
  'BEN': 'Benin',
  'BFA': 'Burkina Faso',
  'BWA': 'Botswana',
  'CAF': 'Den sentralafrikanske republikk', 'central african republic': 'Den sentralafrikanske republikk',
  'CIV': 'Elfenbenskysten', 'ivory coast': 'Elfenbenskysten', "cote d'ivoire": 'Elfenbenskysten',
  'CMR': 'Kamerun', 'cameroon': 'Kamerun',
  'COD': 'DR Kongo', 'democratic republic of the congo': 'DR Kongo', 'dem. rep. congo': 'DR Kongo',
  'COG': 'Republikken Kongo', 'republic of the congo': 'Republikken Kongo', 'congo': 'Republikken Kongo',
  'COM': 'Komorene', 'comoros': 'Komorene',
  'CPV': 'Kapp Verde', 'cape verde': 'Kapp Verde',
  'DJI': 'Djibouti',
  'DZA': 'Algerie', 'algeria': 'Algerie',
  'EGY': 'Egypt',
  'ERI': 'Eritrea',
  'ESH': 'Vest-Sahara', 'western sahara': 'Vest-Sahara',
  'ETH': 'Etiopia', 'ethiopia': 'Etiopia',
  'GAB': 'Gabon',
  'GHA': 'Ghana',
  'GIN': 'Guinea',
  'GMB': 'Gambia', 'the gambia': 'Gambia',
  'GNB': 'Guinea-Bissau',
  'GNQ': 'Ekvatorial-Guinea', 'equatorial guinea': 'Ekvatorial-Guinea',
  'KEN': 'Kenya',
  'LBR': 'Liberia',
  'LBY': 'Libya',
  'LSO': 'Lesotho',
  'MAR': 'Marokko', 'morocco': 'Marokko',
  'MDG': 'Madagaskar', 'madagascar': 'Madagaskar',
  'MLI': 'Mali',
  'MOZ': 'Mosambik', 'mozambique': 'Mosambik',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MWI': 'Malawi',
  'NAM': 'Namibia',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'RWA': 'Rwanda',
  'SDN': 'Sudan',
  'SEN': 'Senegal',
  'SLE': 'Sierra Leone',
  'SOM': 'Somalia',
  'SSD': 'Sør-Sudan', 'south sudan': 'Sør-Sudan',
  'STP': 'Sāo Tomé og Príncipe', 'sao tome and principe': 'Sāo Tomé og Príncipe',
  'SWZ': 'Eswatini', 'swaziland': 'Eswatini',
  'SYC': 'Seychellene', 'seychelles': 'Seychellene',
  'TCD': 'Tsjad', 'chad': 'Tsjad',
  'TGO': 'Togo',
  'TUN': 'Tunisia',
  'TZA': 'Tanzania',
  'UGA': 'Uganda',
  'ZAF': 'Sør-Afrika', 'south africa': 'Sør-Afrika',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe',

  // --- Oseania ---
  'AUS': 'Australia',
  'FJI': 'Fiji',
  'FSM': 'Mikronesiaføderasjonen', 'micronesia': 'Mikronesiaføderasjonen',
  'KIR': 'Kiribati',
  'NCL': 'Ny-Caledonia', 'new caledonia': 'Ny-Caledonia',
  'NRU': 'Nauru',
  'NZL': 'New Zealand',
  'PNG': 'Papua Ny-Guinea', 'papua new guinea': 'Papua Ny-Guinea',
  'PLW': 'Palau',
  'SLB': 'Salomonøyene', 'solomon islands': 'Salomonøyene',
  'TON': 'Tonga',
  'TUV': 'Tuvalu',
  'VUT': 'Vanuatu',
  'WSM': 'Samoa',

  // --- Antarktis ---
  'ATA': 'Antarktis', 'antarctica': 'Antarktis'
};

// Liste over ISO3-koder som har sin egen detaljside i Land/-mappen
window.availableLandPages = ['NOR', 'SWE', 'DNK', 'ITA', 'DEU', 'FIN', 'BEL', 'AUT', 'NLD', 'ISL', 'GBR', 'ESP', 'CHE', 'FRA', 'IRL', 'POL'];

// Globalt kart som kobler alle landnavn (norsk/engelsk/ISO) direkte til sin ISO3-kode
window.isoNameMap = {
  // --- Europa ---
  'alb': 'ALB', 'albania': 'ALB',
  'and': 'AND', 'andorra': 'AND',
  'aut': 'AUT', 'østerrike': 'AUT', 'austria': 'AUT',
  'bel': 'BEL', 'belgia': 'BEL', 'belgium': 'BEL',
  'bgr': 'BGR', 'bulgaria': 'BGR',
  'bih': 'BIH', 'bosnia-hercegovina': 'BIH', 'bosnia and herzegovina': 'BIH', 'bosnia': 'BIH',
  'blr': 'BLR', 'hviterussland': 'BLR', 'belarus': 'BLR',
  'che': 'CHE', 'sveits': 'CHE', 'switzerland': 'CHE',
  'cyp': 'CYP', 'kypros': 'CYP', 'cyprus': 'CYP',
  'cze': 'CZE', 'tsjekkia': 'CZE', 'czech republic': 'CZE', 'czechia': 'CZE',
  'deu': 'DEU', 'tyskland': 'DEU', 'germany': 'DEU',
  'dnk': 'DNK', 'danmark': 'DNK', 'denmark': 'DNK',
  'esp': 'ESP', 'spania': 'ESP', 'spain': 'ESP',
  'est': 'EST', 'estland': 'EST', 'estonia': 'EST',
  'fin': 'FIN', 'finland': 'FIN',
  'fra': 'FRA', 'frankrike': 'FRA', 'france': 'FRA',
  'fro': 'FRO', 'færøyene': 'FRO', 'faroe islands': 'FRO',
  'gbr': 'GBR', 'storbritannia': 'GBR', 'united kingdom': 'GBR', 'great britain': 'GBR',
  'geo': 'GEO', 'georgia': 'GEO',
  'gib': 'GIB', 'gibraltar': 'GIB',
  'grc': 'GRC', 'hellas': 'GRC', 'greece': 'GRC',
  'hrv': 'HRV', 'kroatia': 'HRV', 'croatia': 'HRV',
  'hun': 'HUN', 'ungarn': 'HUN', 'hungary': 'HUN',
  'irl': 'IRL', 'irland': 'IRL', 'ireland': 'IRL',
  'isl': 'ISL', 'island': 'ISL', 'iceland': 'ISL',
  'ita': 'ITA', 'italia': 'ITA', 'italy': 'ITA',
  'kos': 'KOS', 'kosovo': 'KOS',
  'lie': 'LIE', 'liechtenstein': 'LIE',
  'ltu': 'LTU', 'litauen': 'LTU', 'lithuania': 'LTU',
  'lux': 'LUX', 'luxembourg': 'LUX',
  'lva': 'LVA', 'letland': 'LVA', 'latvia': 'LVA',
  'mco': 'MCO', 'monaco': 'MCO',
  'mda': 'MDA', 'moldova': 'MDA',
  'mkd': 'MKD', 'nord-makedonia': 'MKD', 'macedonia': 'MKD', 'north macedonia': 'MKD',
  'mlt': 'MLT', 'malta': 'MLT',
  'mne': 'MNE', 'montenegro': 'MNE',
  'nld': 'NLD', 'nederland': 'NLD', 'netherlands': 'NLD',
  'nor': 'NOR', 'norge': 'NOR', 'norway': 'NOR',
  'pol': 'POL', 'polen': 'POL', 'poland': 'POL',
  'prt': 'PRT', 'portugal': 'PRT',
  'rou': 'ROU', 'romania': 'ROU',
  'rus': 'RUS', 'russland': 'RUS', 'russia': 'RUS',
  'smr': 'SMR', 'san marino': 'SMR',
  'srb': 'SRB', 'serbia': 'SRB',
  'svk': 'SVK', 'slovakia': 'SVK',
  'svn': 'SVN', 'slovenia': 'SVN',
  'swe': 'SWE', 'sverige': 'SWE', 'sweden': 'SWE',
  'ukr': 'UKR', 'ukraina': 'UKR', 'ukraine': 'UKR',
  'vat': 'VAT', 'vatikanstaten': 'VAT', 'vatican city': 'VAT',
  'arm': 'ARM', 'armenia': 'ARM',
  'aze': 'AZE', 'aserbajdsjan': 'AZE', 'azerbaijan': 'AZE',
  'kaz': 'KAZ', 'kasakhstan': 'KAZ', 'kazakhstan': 'KAZ',
  'tur': 'TUR', 'tyrkia': 'TUR', 'turkey': 'TUR',
  'ala': 'ALA', 'åland': 'ALA', 'aland islands': 'ALA',

  // --- Nord-Amerika & Karibia ---
  'abw': 'ABW', 'aruba': 'ABW',
  'aia': 'AIA', 'anguilla': 'AIA',
  'atg': 'ATG', 'antigua og barbuda': 'ATG', 'antigua and barbuda': 'ATG',
  'bhs': 'BHS', 'bahamas': 'BHS', 'the bahamas': 'BHS',
  'blz': 'BLZ', 'belize': 'BLZ',
  'bmu': 'BMU', 'bermuda': 'BMU',
  'brb': 'BRB', 'barbados': 'BRB',
  'can': 'CAN', 'kanada': 'CAN', 'canada': 'CAN',
  'cri': 'CRI', 'costa rica': 'CRI',
  'cub': 'CUB', 'kuba': 'CUB', 'cuba': 'CUB',
  'cym': 'CYM', 'caymanøyene': 'CYM', 'cayman islands': 'CYM',
  'dma': 'DMA', 'dominica': 'DMA',
  'dom': 'DOM', 'den dominikanske republikk': 'DOM', 'dominican republic': 'DOM',
  'glp': 'GLP', 'guadeloupe': 'GLP',
  'grd': 'GRD', 'grenada': 'GRD',
  'grl': 'GRL', 'grønland': 'GRL', 'greenland': 'GRL',
  'gtm': 'GTM', 'guatemala': 'GTM',
  'hnd': 'HND', 'honduras': 'HND',
  'hti': 'HTI', 'haiti': 'HTI',
  'jam': 'JAM', 'jamaica': 'JAM',
  'lca': 'LCA', 'saint lucia': 'LCA',
  'mex': 'MEX', 'meksiko': 'MEX', 'mexico': 'MEX',
  'mtq': 'MTQ', 'martinique': 'MTQ',
  'nic': 'NIC', 'nicaragua': 'NIC',
  'pan': 'PAN', 'panama': 'PAN',
  'pri': 'PRI', 'puerto rico': 'PRI',
  'slv': 'SLV', 'el salvador': 'SLV',
  'tto': 'TTO', 'trinidad og tobago': 'TTO', 'trinidad and tobago': 'TTO',
  'usa': 'USA', 'united states': 'USA', 'united states of america': 'USA',
  'vct': 'VCT', 'saint vincent og grenadinene': 'VCT', 'saint vincent and the grenadines': 'VCT',
  'vir': 'VIR', 'de amerikanske jomfruøyer': 'VIR', 'united states virgin islands': 'VIR',

  // --- Sør-Amerika ---
  'arg': 'ARG', 'argentina': 'ARG',
  'bol': 'BOL', 'bolivia': 'BOL',
  'bra': 'BRA', 'brasil': 'BRA', 'brazil': 'BRA',
  'chl': 'CHL', 'chile': 'CHL',
  'col': 'COL', 'colombia': 'COL',
  'ecu': 'ECU', 'ecuador': 'ECU',
  'flk': 'FLK', 'falklandsøyene': 'FLK', 'falkland islands': 'FLK',
  'guf': 'GUF', 'fransk guyana': 'GUF', 'french guiana': 'GUF',
  'guy': 'GUY', 'guyana': 'GUY',
  'per': 'PER', 'peru': 'PER',
  'pry': 'PRY', 'paraguay': 'PRY',
  'sur': 'SUR', 'surinam': 'SUR', 'suriname': 'SUR',
  'ury': 'URY', 'uruguay': 'URY',
  'ven': 'VEN', 'venezuela': 'VEN',

  // --- Asia ---
  'afg': 'AFG', 'afghanistan': 'AFG',
  'are': 'ARE', 'de forente arabiske emirater': 'ARE', 'united arab emirates': 'ARE', 'uae': 'ARE',
  'bgd': 'BGD', 'bangladesh': 'BGD',
  'bhr': 'BHR', 'bahrain': 'BHR',
  'brn': 'BRN', 'brunei': 'BRN',
  'btn': 'BTN', 'bhutan': 'BTN',
  'chn': 'CHN', 'kina': 'CHN', 'china': 'CHN',
  'idn': 'IDN', 'indonesia': 'IDN',
  'ind': 'IND', 'india': 'IND',
  'isr': 'ISR', 'israel': 'ISR',
  'jor': 'JOR', 'jordan': 'JOR',
  'jpn': 'JPN', 'japan': 'JPN',
  'kgz': 'KGZ', 'kirgisistan': 'KGZ', 'kyrgyzstan': 'KGZ',
  'khm': 'KHM', 'kambodsja': 'KHM', 'cambodia': 'KHM',
  'kor': 'KOR', 'sør-korea': 'KOR', 'south korea': 'KOR', 'korea, republic of': 'KOR',
  'kwt': 'KWT', 'kuwait': 'KWT',
  'lao': 'LAO', 'laos': 'LAO',
  'lbn': 'LBN', 'libanon': 'LBN', 'lebanon': 'LBN',
  'lka': 'LKA', 'sri lanka': 'LKA',
  'mdv': 'MDV', 'maldivene': 'MDV', 'maldives': 'MDV',
  'mmr': 'MMR', 'myanmar': 'MMR',
  'mng': 'MNG', 'mongolia': 'MNG',
  'mys': 'MYS', 'malaysia': 'MYS',
  'npl': 'NPL', 'nepal': 'NPL',
  'omn': 'OMN', 'oman': 'OMN',
  'pak': 'PAK', 'pakistan': 'PAK',
  'phl': 'PHL', 'filippinene': 'PHL', 'philippines': 'PHL',
  'prk': 'PRK', 'nord-korea': 'PRK', 'north korea': 'PRK', 'dem. rep. korea': 'PRK',
  'pse': 'PSE', 'palestina': 'PSE', 'palestine': 'PSE',
  'qat': 'QAT', 'qatar': 'QAT',
  'sau': 'SAU', 'saudi-arabia': 'SAU', 'saudi arabia': 'SAU',
  'sgp': 'SGP', 'singapore': 'SGP',
  'syr': 'SYR', 'syria': 'SYR',
  'tha': 'THA', 'thailand': 'THA',
  'tjk': 'TJK', 'tadsjikistan': 'TJK', 'tajikistan': 'TJK',
  'tkm': 'TKM', 'turkmenistan': 'TKM',
  'tls': 'TLS', 'øst-timor': 'TLS', 'east timor': 'TLS', 'timor-leste': 'TLS',
  'twn': 'TWN', 'taiwan': 'TWN',
  'uzb': 'UZB', 'usbekistan': 'UZB', 'uzbekistan': 'UZB',
  'vnm': 'VNM', 'vietnam': 'VNM',
  'yem': 'YEM', 'jemen': 'YEM', 'yemen': 'YEM',

  // --- Afrika ---
  'ago': 'AGO', 'angola': 'AGO',
  'bdi': 'BDI', 'burundi': 'BDI',
  'ben': 'BEN', 'benin': 'BEN',
  'bfa': 'BFA', 'burkina faso': 'BFA',
  'bwa': 'BWA', 'botswana': 'BWA',
  'caf': 'CAF', 'den sentralafrikanske republikk': 'CAF', 'central african republic': 'CAF',
  'civ': 'CIV', 'elfenbenskysten': 'CIV', 'ivory coast': 'CIV', "cote d'ivoire": 'CIV',
  'cmr': 'CMR', 'kamerun': 'CMR', 'cameroon': 'CMR',
  'cod': 'COD', 'dr kongo': 'COD', 'democratic republic of the congo': 'COD', 'dem. rep. congo': 'COD',
  'cog': 'COG', 'republikken kongo': 'COG', 'republic of the congo': 'COG', 'congo': 'COG',
  'com': 'COM', 'komorene': 'COM', 'comoros': 'COM',
  'cpv': 'CPV', 'kapp verde': 'CPV', 'cape verde': 'CPV',
  'dji': 'DJI', 'djibouti': 'DJI',
  'dza': 'DZA', 'algerie': 'DZA', 'algeria': 'DZA',
  'egy': 'EGY', 'egypt': 'EGY',
  'eri': 'ERI', 'eritrea': 'ERI',
  'esh': 'ESH', 'vest-sahara': 'ESH', 'western sahara': 'ESH',
  'eth': 'ETH', 'etiopia': 'ETH', 'ethiopia': 'ETH',
  'gab': 'GAB', 'gabon': 'GAB',
  'gha': 'GHA', 'ghana': 'GHA',
  'gin': 'GIN', 'guinea': 'GIN',
  'gmb': 'GMB', 'gambia': 'GMB', 'the gambia': 'GMB',
  'gnb': 'GNB', 'guinea-bissau': 'GNB',
  'gnq': 'GNQ', 'ekvatorial-guinea': 'GNQ', 'equatorial guinea': 'GNQ',
  'ken': 'KEN', 'kenya': 'KEN',
  'lbr': 'LBR', 'liberia': 'LBR',
  'lby': 'LBY', 'libya': 'LBY',
  'lso': 'LSO', 'lesotho': 'LSO',
  'mar': 'MAR', 'marokko': 'MAR', 'morocco': 'MAR',
  'mdg': 'MDG', 'madagaskar': 'MDG', 'madagascar': 'MDG',
  'mli': 'MLI', 'mali': 'MLI',
  'moz': 'MOZ', 'mosambik': 'MOZ', 'mozambique': 'MOZ',
  'mrt': 'MRT', 'mauritania': 'MRT',
  'mus': 'MUS', 'mauritius': 'MUS',
  'mwi': 'MWI', 'malawi': 'MWI',
  'nam': 'NAM', 'namibia': 'NAM',
  'ner': 'NER', 'niger': 'NER',
  'nga': 'NGA', 'nigeria': 'NGA',
  'rwa': 'RWA', 'rwanda': 'RWA',
  'sdn': 'SDN', 'sudan': 'SDN',
  'sen': 'SEN', 'senegal': 'SEN',
  'sle': 'SLE', 'sierra leone': 'SLE',
  'som': 'SOM', 'somalia': 'SOM',
  'ssd': 'SSD', 'sør-sudan': 'SSD', 'south sudan': 'SSD',
  'stp': 'STP', 'sāo tomé og príncipe': 'STP', 'sao tome and principe': 'STP',
  'swz': 'SWZ', 'eswatini': 'SWZ', 'swaziland': 'SWZ',
  'syc': 'SYC', 'seychellene': 'SYC', 'seychelles': 'SYC',
  'tcd': 'TCD', 'tsjad': 'TCD', 'chad': 'TCD',
  'tgo': 'TGO', 'togo': 'TGO',
  'tun': 'TUN', 'tunisia': 'TUN',
  'tza': 'TZA', 'tanzania': 'TZA',
  'uga': 'UGA', 'uganda': 'UGA',
  'zaf': 'ZAF', 'sør-afrika': 'ZAF', 'south africa': 'ZAF',
  'zmb': 'ZMB', 'zambia': 'ZMB',
  'zwe': 'ZWE', 'zimbabwe': 'ZWE',

  // --- Oseania ---
  'aus': 'AUS', 'australia': 'AUS',
  'fji': 'FJI', 'fiji': 'FJI',
  'fsm': 'FSM', 'mikronesiaføderasjonen': 'FSM', 'micronesia': 'FSM',
  'kir': 'KIR', 'kiribati': 'KIR',
  'ncl': 'NCL', 'ny-caledonia': 'NCL', 'new caledonia': 'NCL',
  'nru': 'NRU', 'nauru': 'NRU',
  'nzl': 'NZL', 'new zealand': 'NZL',
  'png': 'PNG', 'papua ny-guinea': 'PNG', 'papua new guinea': 'PNG',
  'plw': 'PLW', 'palau': 'PLW',
  'slb': 'SLB', 'salomonøyene': 'SLB', 'solomon islands': 'SLB',
  'ton': 'TON', 'tonga': 'TON',
  'tuv': 'TUV', 'tuvalu': 'TUV',
  'vut': 'VUT', 'vanuatu': 'VUT',
  'wsm': 'WSM', 'samoa': 'WSM',

  // --- Antarktis ---
  'ata': 'ATA', 'antarktis': 'ATA', 'antarctica': 'ATA'
};